repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.4'
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.0"
    hooks:
      - id: mypy
        args:
          [
            "--ignore-missing-imports",
            "--no-warn-no-return",
            "--check-untyped-defs",
          ]
        additional_dependencies:
          - types-protobuf
          - types-requests
          - types-redis
          - types-pyyaml
          - types-aiofiles

  - repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
      - id: unimport

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        files: "\\.(py|.txt|.yaml|.json|.in|.md|.toml|.cfg|.html|.yml)$"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
